### ISSUE TITLE
Why have the option to choose board size?

### ISSUE THREAD

**Issue by RH-sdavey** [Ladia-m/Tic-Tac-Toe#1]
for the sake of learning "how" , yes its very cool, but standard TTT should be 3x3 always..
there could be other games / way to win if the board size is bigger (im thinking "connect 5" or battleships)

**Comment by Ladia-m** [comment]
Yeah, the problem lies in me not understand the name of tic-tac-toe vs connect five. I thought it is the same and my aim is to create connect five game. That is why the resize of board option.
