### ISSUE TITLE
atm, its possible to "overwrite" a previous choice in a square

### ISSUE THREAD

**Issue by RH-sdavey** [Ladia-m/Tic-Tac-Toe#2]
If there is a circle in a cell, I (as a X user) can overwrite it with an X
and can see both visible, [1]
which is the correct "value" thats valid there now?

[1]
![image](https://user-images.githubusercontent.com/32485509/47347950-aa9ffd00-d6b0-11e8-8af8-4634e57bdbf7.png)

**Comment by Ladia-m** [comment]
Will be fixed soon :)

**Comment by Ladia-m** [comment]
Fixed :)
