### ISSUE TITLE
X and O are drawn, gifs dont seem needed

### ISSUE THREAD

**Issue by RH-sdavey** [Ladia-m/Tic-Tac-Toe#3]
as far as I can see, the X and O symbols are 'drawn' instead of coming from the gifs file in the data folder, 
these gif files are no longer required to be there... unless I missed something

https://github.com/Ladia-m/Tic-Tac-Toe/blob/5e8fd6ffc19d5197f6fdd9158829dcde1018f889/Interface.py#L118 has the line : 
letterx = ascii_uppercase[x]

which seems to be unused/outdated variable.

**Comment by Ladia-m** [comment]
Variable letterx will be used for showing logs in game. So it is more human readable.
